a:
	g++ -g -o a ../murmurhash/murmurhash3.h ../murmurhash/murmurhash3.cpp ../hashtable/hashtable.cpp ../hashtable/hashtable.h ../bloomfilter/bloomfilter.h ../bloomfilter/bloomfilter.cpp avl_tree.cpp avl_tree.h main.cpp
